### ISSUE TITLE
Add OS detection in bootstrap.sh

### ISSUE THREAD

**Issue by wrightbradley** [wrightbradley/dotfiles#1]
We should handle different operating systems in bootstrap.sh for certain OS specific operations such as: Python paths and Ansible playbooks

**Comment by the-wright-engineer** [comment]
Not necessarily OS detection, but environment detection option. In Github Codespaces, we need to handle things differently than if we are running on Debian or MacOS systems. To detect and handle, we can use the automatically set environment variables:
`CODESPACES=true
CODESPACE_VSCODE_FOLDER=/workspaces/dotfiles`

or

`uname -a
Linux codespaces_5e8569 5.4.0-1059-azure #62~18.04.1-Ubuntu SMP Tue Sep 14 17:53:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by the-wright-engineer** [comment]
This has been partially completed by https://github.com/the-wright-engineer/dotfiles/commit/7d8bed336aad28b3dddd4364b5d3fdafb77aba59
